# Generated by Django 5.1.3 on 2026-04-25 21:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_barcode_product_image_product_is_active_and_more'),
        ('stock', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, db_index=True, max_length=32, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('confirmed', 'Подтверждён'), ('received', 'Получен'), ('cancelled', 'Отменён')], default='draft', max_length=12, verbose_name='Статус')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Ожидаемая дата')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Дата получения')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier', verbose_name='Поставщик')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='stock.warehouse', verbose_name='Склад приёмки')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на закупку',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Закуп. цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='products.product', verbose_name='Товар')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Позиция закупки',
                'verbose_name_plural': 'Позиции закупки',
            },
        ),
        migrations.CreateModel(
            name='PurchasePriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_price_history', to='products.product')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'История закуп. цены',
                'verbose_name_plural': 'История закуп. цен',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['status'], name='purchases_p_status_7fddca_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['-created_at'], name='purchases_p_created_2260fa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepricehistory',
            index=models.Index(fields=['supplier', 'product', '-recorded_at'], name='purchases_p_supplie_fa6c46_idx'),
        ),
    ]
