# Generated by Django 5.1.3 on 2026-04-25 21:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_barcode_product_image_product_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=32, verbose_name='Код')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_default', models.BooleanField(default=False, help_text='Только один склад может быть по умолчанию', verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склады',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'Приход'), ('out', 'Расход'), ('transfer', 'Перемещение'), ('inventory', 'Инвентаризация'), ('reserve', 'Резервирование'), ('unreserve', 'Снятие резерва'), ('return', 'Возврат')], max_length=12, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Положительное число; знак определяется типом операции', max_digits=14, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Цена за ед.')),
                ('reference', models.CharField(blank=True, help_text='Например: PO-2026-0001 или AQ-2026-0042', max_length=64, verbose_name='Документ-основание')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.product', verbose_name='Товар')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='stock.warehouse', verbose_name='Склад')),
                ('warehouse_to', models.ForeignKey(blank=True, help_text='Только для перемещений', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='stock.warehouse', verbose_name='Склад-получатель')),
            ],
            options={
                'verbose_name': 'Движение по складу',
                'verbose_name_plural': 'Движения по складу',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='stock_stock_created_721a0f_idx'), models.Index(fields=['product'], name='stock_stock_product_e1ff8e_idx'), models.Index(fields=['type'], name='stock_stock_type_05a173_idx')],
            },
        ),
    ]
