# Generated by Django 5.1.3 on 2026-04-25 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientinteraction_clienttag_clienttask_and_more'),
        ('users', '0002_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client_profile',
            field=models.ForeignKey(blank=True, help_text='Заполняется только для пользователей-клиентов кабинета', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='clients.client', verbose_name='Связанный клиент'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Супер-администратор'), ('director', 'Директор'), ('admin', 'Администратор'), ('manager', 'Менеджер'), ('warehouse', 'Кладовщик'), ('accountant', 'Бухгалтер'), ('purchaser', 'Закупщик'), ('client', 'Клиент')], default='manager', max_length=20, verbose_name='Роль'),
        ),
    ]
