# Generated by Django 5.1.3 on 2026-04-25 21:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AquaLine', max_length=255, verbose_name='Название компании')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Юр. наименование')),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=32, verbose_name='КПП')),
                ('address', models.TextField(blank=True, verbose_name='Юр. адрес')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('bank_details', models.TextField(blank=True, verbose_name='Банковские реквизиты')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип')),
                ('default_currency', models.CharField(default='TJS', max_length=3, verbose_name='Валюта по умолчанию')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Ставка налога %')),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профиль компании',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='Курс к TJS')),
                ('date', models.DateField(verbose_name='Дата')),
                ('source', models.CharField(blank=True, max_length=64, verbose_name='Источник')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='settings_app.currency')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
