# Generated by Django 5.1.3 on 2026-04-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('physical', 'Физическое лицо'), ('legal', 'Юридическое лицо'), ('entrepreneur', 'ИП')], default='physical', max_length=20, verbose_name='Тип')),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('segment', models.CharField(choices=[('retail', 'Розница'), ('b2b', 'B2B'), ('dealer', 'Дилер'), ('other', 'Прочее')], default='retail', max_length=20, verbose_name='Сегмент')),
                ('status', models.CharField(choices=[('lead', 'Лид'), ('active', 'Активный'), ('vip', 'VIP'), ('blocked', 'Заблокирован')], default='lead', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-created_at'],
            },
        ),
    ]
