# Generated by Django 5.1.3 on 2026-04-25 21:21

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('call', 'Звонок'), ('meeting', 'Встреча'), ('email', 'Email'), ('messenger', 'Мессенджер'), ('other', 'Прочее')], max_length=12)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='clients.client')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(default='#8E7CF8', max_length=7)),
                ('clients', models.ManyToManyField(blank=True, related_name='tags', to='clients.client')),
            ],
            options={
                'verbose_name': 'Тег клиента',
                'verbose_name_plural': 'Теги клиентов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_tasks', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='clients.client')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type', models.CharField(choices=[('physical', 'Физическое лицо'), ('legal', 'Юридическое лицо'), ('entrepreneur', 'ИП')], default='physical', max_length=20, verbose_name='Тип')),
                ('inn', models.CharField(blank=True, max_length=32, verbose_name='ИНН')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('segment', models.CharField(choices=[('retail', 'Розница'), ('b2b', 'B2B'), ('dealer', 'Дилер'), ('other', 'Прочее')], default='retail', max_length=20, verbose_name='Сегмент')),
                ('status', models.CharField(choices=[('lead', 'Лид'), ('active', 'Активный'), ('vip', 'VIP'), ('blocked', 'Заблокирован')], default='lead', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Обновлён')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'verbose_name': 'historical Клиент',
                'verbose_name_plural': 'historical Клиенты',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
