# Generated by Django 5.1.3 on 2026-04-25 19:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('kg', 'кг'), ('l', 'л'), ('pack', 'уп')], default='pcs', max_length=10, verbose_name='Ед. изм.')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Розничная цена')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Остаток')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['sku'], name='products_pr_sku_ca0cdc_idx')],
            },
        ),
    ]
