# Generated by Django 5.1.3 on 2026-04-25 21:21

import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Триггер для уведомления о пополнении', max_digits=12, verbose_name='Мин. остаток'),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, verbose_name='Артикул')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('unit', models.CharField(choices=[('pcs', 'шт'), ('m', 'м'), ('kg', 'кг'), ('l', 'л'), ('pack', 'уп')], default='pcs', max_length=10, verbose_name='Ед. изм.')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Закупочная цена')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Розничная цена')),
                ('stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Остаток')),
                ('min_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Триггер для уведомления о пополнении', max_digits=12, verbose_name='Мин. остаток')),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Штрихкод')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Товар',
                'verbose_name_plural': 'historical Товары',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
