# Generated by Django 5.1.3 on 2026-04-25 21:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_barcode_product_image_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='reserved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Зарезервировано под подтверждённые заказы', max_digits=12, verbose_name='Резерв'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Зарезервировано под подтверждённые заказы', max_digits=12, verbose_name='Резерв'),
        ),
    ]
